[package]
name = "sire-run"
version = "0.1.0"
authors = ["Christian Poveda <christianpoveda@protonmail.com>"]
edition = "2018"

[dependencies]
rustc-workspace-hack = "1.0.0"
sire = { path = "../sire" }
sire-smt = { path = "../sire_smt" }
